base_url = "https://dalia.rojasvallejo.xyz"
title = "DaliaWeb"
description = "Dalia Rojas es una desarrolladora latinoamericana que usa esta página para explorar sus proyectos personales y plasmar sus pensamientos."
default_language = "es"
theme = "anemone"
compile_sass = false
minify_html = true
generate_feed = true
feed_filename = "atom.xml"
author = "Dalia Rojas Vallejo"
taxonomies = [{ name = "tags", feed = true }]
build_search_index = false

[markdown]
highlight_code = true
extra_syntaxes_and_themes = ["highlight-themes"]
highlight_theme = "Catppuccin Mocha"
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true
lazy_async_image = true

[extra]
list_pages = false
default_theme = "dark"
display_author = false
twitter_card = true
header_nav = [
  { url = "/", name_es = "/principal/" },
  { url = "/info", name_es = "/info/" },
  { url = "/blog", name_es = "/blog/" },
  { url = "/proyectos", name_es = "/proyectos/" },
]
